// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Menu_screen_init(void)
{
    ui_Menu = lv_obj_create(NULL);
    lv_obj_add_flag(ui_Menu, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_Menu, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Menu, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_Menu, &ui__temporary_image, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Tempature = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_Tempature);
    lv_obj_set_width(ui_Tempature, 120);
    lv_obj_set_height(ui_Tempature, 120);
    lv_obj_set_x(ui_Tempature, 55);
    lv_obj_set_y(ui_Tempature, -38);
    lv_obj_set_align(ui_Tempature, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Tempature, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempArc = lv_arc_create(ui_Tempature);
    lv_obj_set_width(ui_TempArc, 110);
    lv_obj_set_height(ui_TempArc, 110);
    lv_obj_set_x(ui_TempArc, 3);
    lv_obj_set_y(ui_TempArc, 4);
    lv_obj_set_align(ui_TempArc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempArc, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_clear_flag(ui_TempArc, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_TempArc, 50);
    lv_obj_set_style_arc_color(ui_TempArc, lv_color_hex(0xDAD8D8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempArc, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_TempArc, lv_color_hex(0x038ED2), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_TempArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_TempArc, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TempArc, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempArc, lv_color_hex(0x10BC9C), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempArc, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_TempatureNum = lv_obj_create(ui_Tempature);
    lv_obj_remove_style_all(ui_TempatureNum);
    lv_obj_set_width(ui_TempatureNum, 50);
    lv_obj_set_height(ui_TempatureNum, 50);
    lv_obj_set_x(ui_TempatureNum, 3);
    lv_obj_set_y(ui_TempatureNum, 3);
    lv_obj_set_align(ui_TempatureNum, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempatureNum, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempLabel = lv_label_create(ui_TempatureNum);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, 0);
    lv_obj_set_y(ui_TempLabel, 1);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "Temp");
    lv_obj_add_flag(ui_TempLabel, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_TempLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_Humidity);
    lv_obj_set_width(ui_Humidity, 110);
    lv_obj_set_height(ui_Humidity, 40);
    lv_obj_set_x(ui_Humidity, -62);
    lv_obj_set_y(ui_Humidity, 48);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Humidity, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humidPic = lv_obj_create(ui_Humidity);
    lv_obj_remove_style_all(ui_humidPic);
    lv_obj_set_width(ui_humidPic, 30);
    lv_obj_set_height(ui_humidPic, 30);
    lv_obj_set_x(ui_humidPic, -40);
    lv_obj_set_y(ui_humidPic, -1);
    lv_obj_set_align(ui_humidPic, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_humidPic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_humidPic, &ui_img_weather_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_humidPic, lv_color_hex(0x3D4CA0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_humidPic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidText = lv_obj_create(ui_Humidity);
    lv_obj_remove_style_all(ui_HumidText);
    lv_obj_set_width(ui_HumidText, 65);
    lv_obj_set_height(ui_HumidText, 30);
    lv_obj_set_x(ui_HumidText, 7);
    lv_obj_set_y(ui_HumidText, 0);
    lv_obj_set_align(ui_HumidText, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HumidText, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HumidLabel = lv_label_create(ui_HumidText);
    lv_obj_set_width(ui_HumidLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidLabel, -6);
    lv_obj_set_y(ui_HumidLabel, -1);
    lv_obj_set_align(ui_HumidLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidLabel, "humid");
    lv_obj_add_flag(ui_HumidLabel, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_HumidLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_Time);
    lv_obj_set_width(ui_Time, 235);
    lv_obj_set_height(ui_Time, 50);
    lv_obj_set_x(ui_Time, -1);
    lv_obj_set_y(ui_Time, -133);
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ClockPic = lv_obj_create(ui_Time);
    lv_obj_remove_style_all(ui_ClockPic);
    lv_obj_set_width(ui_ClockPic, 50);
    lv_obj_set_height(ui_ClockPic, 50);
    lv_obj_set_x(ui_ClockPic, -92);
    lv_obj_set_y(ui_ClockPic, -2);
    lv_obj_set_align(ui_ClockPic, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ClockPic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ClockPic, &ui_img_time_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_ClockPic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_ClockPic, lv_color_hex(0xB63707), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_ClockPic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeContent = lv_obj_create(ui_Time);
    lv_obj_remove_style_all(ui_TimeContent);
    lv_obj_set_width(ui_TimeContent, 190);
    lv_obj_set_height(ui_TimeContent, 50);
    lv_obj_set_x(ui_TimeContent, 24);
    lv_obj_set_y(ui_TimeContent, -1);
    lv_obj_set_align(ui_TimeContent, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimeContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Hour = lv_label_create(ui_TimeContent);
    lv_obj_set_width(ui_Hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hour, -65);
    lv_obj_set_y(ui_Hour, 9);
    lv_obj_set_align(ui_Hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hour, "Hour");
    lv_obj_set_style_text_font(ui_Hour, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minute = lv_label_create(ui_TimeContent);
    lv_obj_set_width(ui_Minute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Minute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Minute, -6);
    lv_obj_set_y(ui_Minute, 9);
    lv_obj_set_align(ui_Minute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Minute, "Minute");
    lv_obj_set_style_text_font(ui_Minute, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Second = lv_label_create(ui_TimeContent);
    lv_obj_set_width(ui_Second, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Second, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Second, 59);
    lv_obj_set_y(ui_Second, 9);
    lv_obj_set_align(ui_Second, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Second, "Second");
    lv_obj_set_style_text_font(ui_Second, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Year = lv_label_create(ui_TimeContent);
    lv_obj_set_width(ui_Year, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Year, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Year, -63);
    lv_obj_set_y(ui_Year, -10);
    lv_obj_set_align(ui_Year, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Year, "Year");
    lv_obj_set_style_text_font(ui_Year, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Month = lv_label_create(ui_TimeContent);
    lv_obj_set_width(ui_Month, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Month, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Month, -5);
    lv_obj_set_y(ui_Month, -10);
    lv_obj_set_align(ui_Month, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Month, "Month");
    lv_obj_set_style_text_font(ui_Month, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Day = lv_label_create(ui_TimeContent);
    lv_obj_set_width(ui_Day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Day, 57);
    lv_obj_set_y(ui_Day, -10);
    lv_obj_set_align(ui_Day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Day, "Day");
    lv_obj_set_style_text_font(ui_Day, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Picture = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_Picture);
    lv_obj_set_width(ui_Picture, 100);
    lv_obj_set_height(ui_Picture, 100);
    lv_obj_set_x(ui_Picture, -59);
    lv_obj_set_y(ui_Picture, -42);
    lv_obj_set_align(ui_Picture, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Picture, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Picture, &ui_img_iu1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_Light);
    lv_obj_set_width(ui_Light, 110);
    lv_obj_set_height(ui_Light, 40);
    lv_obj_set_x(ui_Light, 62);
    lv_obj_set_y(ui_Light, 47);
    lv_obj_set_align(ui_Light, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Light, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DarkPic = lv_obj_create(ui_Light);
    lv_obj_remove_style_all(ui_DarkPic);
    lv_obj_set_width(ui_DarkPic, 30);
    lv_obj_set_height(ui_DarkPic, 30);
    lv_obj_set_x(ui_DarkPic, -40);
    lv_obj_set_y(ui_DarkPic, -1);
    lv_obj_set_align(ui_DarkPic, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DarkPic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_DarkPic, &ui_img_dark_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_DarkPic, lv_color_hex(0x030215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_DarkPic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DarkContain = lv_obj_create(ui_Light);
    lv_obj_remove_style_all(ui_DarkContain);
    lv_obj_set_width(ui_DarkContain, 62);
    lv_obj_set_height(ui_DarkContain, 30);
    lv_obj_set_x(ui_DarkContain, 7);
    lv_obj_set_y(ui_DarkContain, 0);
    lv_obj_set_align(ui_DarkContain, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DarkContain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DarkLabel = lv_label_create(ui_DarkContain);
    lv_obj_set_width(ui_DarkLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DarkLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DarkLabel, 0);
    lv_obj_set_y(ui_DarkLabel, -1);
    lv_obj_set_align(ui_DarkLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DarkLabel, "intens");
    lv_obj_add_flag(ui_DarkLabel, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_DarkLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2 = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_CO2);
    lv_obj_set_width(ui_CO2, 110);
    lv_obj_set_height(ui_CO2, 40);
    lv_obj_set_x(ui_CO2, -62);
    lv_obj_set_y(ui_CO2, 90);
    lv_obj_set_align(ui_CO2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CO2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CO2Pic = lv_obj_create(ui_CO2);
    lv_obj_remove_style_all(ui_CO2Pic);
    lv_obj_set_width(ui_CO2Pic, 30);
    lv_obj_set_height(ui_CO2Pic, 30);
    lv_obj_set_x(ui_CO2Pic, -40);
    lv_obj_set_y(ui_CO2Pic, -1);
    lv_obj_set_align(ui_CO2Pic, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CO2Pic, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_CO2Pic, &ui_img_co2_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_CO2Pic, lv_color_hex(0xB32611), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_CO2Pic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CO2Text = lv_obj_create(ui_CO2);
    lv_obj_remove_style_all(ui_CO2Text);
    lv_obj_set_width(ui_CO2Text, 65);
    lv_obj_set_height(ui_CO2Text, 30);
    lv_obj_set_x(ui_CO2Text, 7);
    lv_obj_set_y(ui_CO2Text, 0);
    lv_obj_set_align(ui_CO2Text, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CO2Text, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CO2Label = lv_label_create(ui_CO2Text);
    lv_obj_set_width(ui_CO2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CO2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CO2Label, -6);
    lv_obj_set_y(ui_CO2Label, -1);
    lv_obj_set_align(ui_CO2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CO2Label, "CO2");
    lv_obj_add_flag(ui_CO2Label, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_CO2Label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Controlpage = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_Controlpage);
    lv_obj_set_width(ui_Controlpage, 30);
    lv_obj_set_height(ui_Controlpage, 30);
    lv_obj_set_x(ui_Controlpage, 43);
    lv_obj_set_y(ui_Controlpage, 109);
    lv_obj_set_align(ui_Controlpage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Controlpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Controlpage, &ui_img_icn_control_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Controlpage, lv_color_hex(0x0F24B0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Controlpage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TempLabel, ui_event_TempLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HumidLabel, ui_event_HumidLable, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Hour, ui_event_Hour, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Minute, ui_event_Minute, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Second, ui_event_Second, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Year, ui_event_Year, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Month, ui_event_Month, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Day, ui_event_Day, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DarkLabel, ui_event_DarkLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CO2Label, ui_event_CO2Lable, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Controlpage, ui_event_Controlpage, LV_EVENT_ALL, NULL);

}
