// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Message
void ui_Message_screen_init(void);
lv_obj_t *ui_Message;
lv_obj_t *ui_Tempature;
void ui_event_TempArc(lv_event_t *e);
lv_obj_t *ui_TempArc;
lv_obj_t *ui_TempatureNum;
void ui_event_TempLabel(lv_event_t *e);
lv_obj_t *ui_TempLabel;
lv_obj_t *ui_Humidity;
lv_obj_t *ui_humidPic;
lv_obj_t *ui_HumidText;
void ui_event_HumidLable(lv_event_t *e);
lv_obj_t *ui_HumidLabel;
lv_obj_t *ui_Led1;
lv_obj_t *ui_Led1Text;
void ui_event_Led1Switch(lv_event_t *e);
lv_obj_t *ui_Led1Switch;
lv_obj_t *ui_Led2;
lv_obj_t *ui_Led2Text;
void ui_event_Led2Switch(lv_event_t *e);
lv_obj_t *ui_Led2Switch;
lv_obj_t *ui_Time;
lv_obj_t *ui_ClockPic;
lv_obj_t *ui_TimeContent;
void ui_event_Hour(lv_event_t *e);
lv_obj_t *ui_Hour;
void ui_event_Minute(lv_event_t *e);
lv_obj_t *ui_Minute;
void ui_event_Second(lv_event_t *e);
lv_obj_t *ui_Second;
lv_obj_t *ui_Picture;
void ui_event_Beep(lv_event_t *e);
lv_obj_t *ui_Beep;
lv_obj_t *ui_BeepText;
lv_obj_t *ui_BeepSwitch;
lv_obj_t *ui_Motor;
lv_obj_t *ui_MotorText;
lv_obj_t *ui_MotorSwitch;
lv_obj_t *ui_Light;
lv_obj_t *ui_DarkPic;
lv_obj_t *ui_DarkContain;
void ui_event_DarkLabel(lv_event_t *e);
lv_obj_t *ui_DarkLabel;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_bg[2] = {&ui_img_bg1_png, &ui_img_bg4_png};
const lv_img_dsc_t *ui_imgset_weather_[1] = {&ui_img_weather_1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_TempArc(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        Detect_From_Tempature(e);
    }
}
void ui_event_TempLabel(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        Get_From_Tempature(e);
    }
}
void ui_event_HumidLable(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        Get_from_Humidity(e);
    }
}
void ui_event_Led1Switch(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED && !lv_obj_has_state(target, LV_STATE_CHECKED))
    {
        LED1_OFF(e);
    }
    if (event_code == LV_EVENT_VALUE_CHANGED && lv_obj_has_state(target, LV_STATE_CHECKED))
    {
        LED1_Open(e);
    }
}
void ui_event_Led2Switch(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED && !lv_obj_has_state(target, LV_STATE_CHECKED))
    {
        LED2_Off(e);
    }
    if (event_code == LV_EVENT_VALUE_CHANGED && lv_obj_has_state(target, LV_STATE_CHECKED))
    {
        LED2_Open(e);
    }
}
void ui_event_Hour(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        Get_From_Hour(e);
    }
}
void ui_event_Minute(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        Get_From_Min(e);
    }
}
void ui_event_Second(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        Get_From_Sec(e);
    }
}
void ui_event_Beep(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED && !lv_obj_has_state(target, LV_STATE_CHECKED))
    {
        Beep_Close(e);
    }
    if (event_code == LV_EVENT_CLICKED)
    {
        Beep_Open(e);
    }
}
void ui_event_DarkLabel(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_VALUE_CHANGED)
    {
        Get_from_Light(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Message_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Message);
}
