// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Message
void ui_Message_screen_init(void);
extern lv_obj_t * ui_Message;
extern lv_obj_t * ui_Tempature;
void ui_event_TempArc(lv_event_t * e);
extern lv_obj_t * ui_TempArc;
extern lv_obj_t * ui_TempatureNum;
void ui_event_TempLabel(lv_event_t * e);
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_humidPic;
extern lv_obj_t * ui_HumidText;
void ui_event_HumidLable(lv_event_t * e);
extern lv_obj_t * ui_HumidLabel;
extern lv_obj_t * ui_Led1;
extern lv_obj_t * ui_Led1Text;
void ui_event_Led1Switch(lv_event_t * e);
extern lv_obj_t * ui_Led1Switch;
extern lv_obj_t * ui_Led2;
extern lv_obj_t * ui_Led2Text;
void ui_event_Led2Switch(lv_event_t * e);
extern lv_obj_t * ui_Led2Switch;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_ClockPic;
extern lv_obj_t * ui_TimeContent;
void ui_event_Hour(lv_event_t * e);
extern lv_obj_t * ui_Hour;
void ui_event_Minute(lv_event_t * e);
extern lv_obj_t * ui_Minute;
void ui_event_Second(lv_event_t * e);
extern lv_obj_t * ui_Second;
extern lv_obj_t * ui_Picture;
void ui_event_Beep(lv_event_t * e);
extern lv_obj_t * ui_Beep;
extern lv_obj_t * ui_BeepText;
extern lv_obj_t * ui_BeepSwitch;
extern lv_obj_t * ui_Motor;
extern lv_obj_t * ui_MotorText;
extern lv_obj_t * ui_MotorSwitch;
extern lv_obj_t * ui_Light;
extern lv_obj_t * ui_DarkPic;
extern lv_obj_t * ui_DarkContain;
void ui_event_DarkLabel(lv_event_t * e);
extern lv_obj_t * ui_DarkLabel;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_weather_1_png);    // assets/weather_1.png
LV_IMG_DECLARE(ui_img_time_png);    // assets/time.png
LV_IMG_DECLARE(ui_img_iu_png);    // assets/iu.png
LV_IMG_DECLARE(ui_img_dark_png);    // assets/dark.png
LV_IMG_DECLARE(ui_img_bg1_png);    // assets/bg1.png
LV_IMG_DECLARE(ui_img_bg4_png);    // assets/bg4.png



LV_FONT_DECLARE(ui_font_Number);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
