// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Detect_From_Tempature(lv_event_t * e);
void Get_From_Tempature(lv_event_t * e);
void Get_from_Humidity(lv_event_t * e);
void LED1_OFF(lv_event_t * e);
void LED1_Open(lv_event_t * e);
void LED2_Off(lv_event_t * e);
void LED2_Open(lv_event_t * e);
void Get_From_Hour(lv_event_t * e);
void Get_From_Min(lv_event_t * e);
void Get_From_Sec(lv_event_t * e);
void Beep_Close(lv_event_t * e);
void Beep_Open(lv_event_t * e);
void Get_from_Light(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
