// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Get_From_Tempature(lv_event_t * e);
void Get_from_Humidity(lv_event_t * e);
void Get_From_Hour(lv_event_t * e);
void Get_From_Min(lv_event_t * e);
void Get_From_Sec(lv_event_t * e);
void Get_From_Year(lv_event_t * e);
void Get_From_Month(lv_event_t * e);
void Get_From_Day(lv_event_t * e);
void Get_from_Light(lv_event_t * e);
void Get_from_CO2(lv_event_t * e);
void LED1_Open(lv_event_t * e);
void LED1_OFF(lv_event_t * e);
void LED2_OPEN(lv_event_t * e);
void LED2_OFF(lv_event_t * e);
void BEEP_OPEN(lv_event_t * e);
void BEEP_OFF(lv_event_t * e);
void Motor_On(lv_event_t * e);
void Motor_Off(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
