// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "main.h"
#include "IH_DataManage.h"
void Get_From_Tempature(lv_event_t *e)
{
	static char Temp_buf[8];
	sprintf(Temp_buf, "%d°C", IH_Family.DTH11.tempature);
	lv_label_set_text_fmt(e->target, Temp_buf);
	lv_arc_set_value(ui_TempArc, IH_Family.DTH11.tempature);
}

void Get_from_Humidity(lv_event_t *e)
{
	static char Humid_buf[8];
	sprintf(Humid_buf, "%d Per", IH_Family.DTH11.humidity);
	lv_label_set_text_fmt(e->target, Humid_buf);
}

void Get_From_Hour(lv_event_t *e)
{
	static char Lv_Hour[6];
	sprintf(Lv_Hour, "%d h", IH_Family.NOWTIME.Hours);
	lv_label_set_text_fmt(e->target, Lv_Hour);
}

void Get_From_Min(lv_event_t *e)
{
	static char Lv_Minute[6];
	sprintf(Lv_Minute, "%d m", IH_Family.NOWTIME.Minutes);
	lv_label_set_text_fmt(e->target, Lv_Minute);
}

void Get_From_Sec(lv_event_t *e)
{
	static char Lv_Second[6];
	sprintf(Lv_Second, "%d s", IH_Family.NOWTIME.Seconds);
	lv_label_set_text_fmt(e->target, Lv_Second);
}

void Get_From_Year(lv_event_t *e)
{
	static char Lv_Years[6];
	sprintf(Lv_Years, "%d Y",(2000 + IH_Family.NOWTIME.Year));
	lv_label_set_text_fmt(e->target, Lv_Years);
}

void Get_From_Month(lv_event_t *e)
{
	static char Lv_Months[6];
	sprintf(Lv_Months, "%d M", IH_Family.NOWTIME.Month);
	lv_label_set_text_fmt(e->target, Lv_Months);
}

void Get_From_Day(lv_event_t *e)
{
	static char Lv_Day[4];
	sprintf(Lv_Day, "%d D", IH_Family.NOWTIME.Date);
	lv_label_set_text_fmt(e->target, Lv_Day);
}

void Get_from_Light(lv_event_t *e)
{
	static char LightSensor_buf[8];
	sprintf(LightSensor_buf, "%d LUX", IH_Family.Light.Light_Value);
	lv_label_set_text_fmt(e->target, LightSensor_buf);
}

void Get_from_CO2(lv_event_t *e)
{
	static char MQ2Sensor_buf[8];
	sprintf(MQ2Sensor_buf, "%d PPM", IH_Family.CO2.Concentration_Value);
	lv_label_set_text_fmt(e->target, MQ2Sensor_buf);
}

void LED1_Open(lv_event_t *e)
{
	HAL_GPIO_WritePin(LED1_GPIO_Port, LED1_Pin, GPIO_PIN_RESET);
}

void LED1_OFF(lv_event_t *e)
{
	HAL_GPIO_WritePin(LED1_GPIO_Port, LED1_Pin, GPIO_PIN_SET);
}

void LED2_OPEN(lv_event_t *e)
{
	HAL_GPIO_WritePin(LED2_GPIO_Port, LED2_Pin, GPIO_PIN_RESET);
}

void LED2_OFF(lv_event_t *e)
{
	HAL_GPIO_WritePin(LED2_GPIO_Port, LED2_Pin, GPIO_PIN_SET);
}

void BEEP_OPEN(lv_event_t *e)
{
	HAL_GPIO_WritePin(BEEP_GPIO_Port, BEEP_Pin, GPIO_PIN_RESET);
}

void BEEP_OFF(lv_event_t *e)
{
	HAL_GPIO_WritePin(BEEP_GPIO_Port, BEEP_Pin, GPIO_PIN_SET);
}

void Motor_On(lv_event_t *e)
{
	// Your code here
}

void Motor_Off(lv_event_t *e)
{
	// Your code here
}
